# version: "3.9"
# services:
#   scraper:
#     build: .
#     depends_on:
#       - db
#     volumes:
#       - .:/app

#   db:
#     image: postgres:14
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydb
#     ports:
#       - "5433:5432"
version: "3.9"
services:
  scraper:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"  # Exposing PostgreSQL on port 5433

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Default login email
      PGADMIN_DEFAULT_PASSWORD: admin          # Default login password
    ports:
      - "5050:80"  # pgAdmin will be accessible on http://localhost:5050
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persist pgAdmin data

volumes:
  pgadmin_data:  # Volume to persist pgAdmin settings and data
